version: '3.1'

services:
  db:
    image: mysql:8.3.0
    ports:
      - 3307:3306
    env_file:
      - .env.production

  test_db:
    image: mysql:8.3.0
    ports:
      - 3308:3306
    env_file:
      - .env.dev
